name: Run tests

on:
  schedule:
    - cron: '0 5 * * *'
  pull_request:
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    name: Test Suite
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: ml-tto-dev

      - name: Install ml-tto
        shell: bash -l {0}
        run: |
          pip install -e ".[dev]"

      - name: Test environment conda package list
        shell: bash -l {0}
        run: |
          conda list

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          echo -e '## Test results\n\n```' >> "$GITHUB_STEP_SUMMARY"
          pytest ml_tto/tests -v 2>&1 | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
